### ISSUE TITLE
Tact3

### ISSUE THREAD

**Issue by brayandm** [ton-community/tact-challenge#4]
Hello, in the formula priceA = amountOfJettonAOnContract * decimal / amountOfJettonBOnContract, what will happen if amountOfJettonBOnContract is 0? the price is undefined? Also when you swap

**Comment by aSpite** [comment]
I think this applies to a situation where there are not enough tokens on the contract to send, and you just need to return the tokens.

**Comment by brayandm** [comment]
> I think this applies to a situation where there are not enough tokens on the contract to send, and you just need to return the tokens.

yes but, in the calculation of price what price should we print? I mean, we need to return an integer
